import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FollowerPointerCard } from "@/components/ui/following-pointer";
import { Navbar } from "@/components/Navbar";
import { Spotlight } from "@/components/ui/Spotlight";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        {/* <Spotlight
          className="-top-40 left-0 md:left-60 md:-top-20"
          fill="red"
        /> */}

        <Navbar />
        <div className="h-[50rem] w-full dark:bg-black bg-white  dark:bg-grid-white/[0.2] bg-grid-black/[0.2] relative flex items-center justify-center">
          {/* Radial gradient for the container to give a faded look */}
          <div className="absolute pointer-events-none inset-0 flex items-center justify-center dark:bg-black bg-white [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]"></div>
          {children}
        </div>

      </body>
    </html>
  );
}
