import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FollowerPointerCard } from "@/components/ui/following-pointer";
import { Navbar } from "@/components/Navbar";
import { Spotlight } from "@/components/ui/Spotlight";
import { TracingBeam } from "@/components/ui/tracing-beam";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>


          {/* <Navbar /> */}

          {children}
      </body>
    </html>
  );
}
